//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignuoLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    using CompareAttribute = System.Web.Mvc.CompareAttribute;

    public partial class UserInf
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Поле не повинно бути порожнiм")]
        [Display(Name ="ФIО")]
        public string full_name { get; set; }
        [Required(ErrorMessage = "Поле не повинно бути порожнiм")]
        [Display(Name = "Вiк")]
        public int age { get; set; }
       // public List<SelectListItem> AvailableCities { get; set; }
        [Required(ErrorMessage = "Поле не повинно бути порожнiм")]
        [Display(Name = "Регiональний центр")]
        public string regional_center { get; set; }
        
        [Required(ErrorMessage = "Поле не повинно бути порожнiм")]
        [Display(Name = "Пошта")]
        public string email { get; set; }
        [Display(Name = "Телефон")]
        public string phone { get; set; }
        
        [Required(ErrorMessage = "Поле не повинно бути порожнiм")]
        [Display(Name = "Пароль")]
        [StringLength(100, ErrorMessage = "Поле {0} должно иметь минимум {2} и максимум {1} символов.", MinimumLength = 8)]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "Поле не повинно бути порожнiм")]
        [Display(Name = "Повторiть пароль")]
        [DataType(DataType.Password)]
        [NotMapped]
        [System.ComponentModel.DataAnnotations.Compare("password", ErrorMessage = "Пароли не совпадают")]
        public string RePassword { get; set; }

    }
}
